services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  atamai-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/aiatamai/atamai-ai:${ATAMAI_DOCKER_TAG-main}
    container_name: atamai-ai
    volumes:
      - atamai-ai:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${ATAMAI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'ATAMAI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  atamai-ai: {}
